import Car4 from "../../assets/imgs/prods/car44.jpg";

export const productData = [
  {
    id: 1,
    name: "Mercedece HutchBack German",
    year: 2005,
    price: "1,500,000",
    status: "Negotiatiable",
    millage: "32k",
    seller: "owner",
    img: Car4,
  },
  {
    id: 1,
    name: "",
    year: "",
    price: "",
    status: "Negotiatiable",
    millage: "",
    seller: "owner",
    img: Car4,
  },
  {
    id: 1,
    name: "",
    year: "",
    price: "",
    status: "Negotiatiable",
    millage: "",
    seller: "owner",
    img: Car4,
  },
  {
    id: 1,
    name: "",
    year: "",
    price: "",
    status: "Negotiatiable",
    millage: "",
    seller: "owner",
    img: Car4,
  },
  {
    id: 1,
    name: "",
    year: "",
    price: "",
    status: "Negotiatiable",
    millage: "",
    seller: "owner",
    img: Car4,
  },
  {
    id: 1,
    name: "",
    year: "",
    price: "",
    status: "Negotiatiable",
    millage: "",
    seller: "owner",
    img: Car4,
  },
  {
    id: 1,
    name: "",
    year: "",
    price: "",
    status: "Negotiatiable",
    millage: "",
    seller: "owner",
    img: Car4,
  },
  {
    id: 1,
    name: "",
    year: "",
    price: "",
    status: "Negotiatiable",
    millage: "",
    seller: "owner",
    img: Car4,
  },
];
